# This rule is not used by the project cluster-secret-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the clustersecret.pocteo.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-secret-controller
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-editor-role
rules:
- apiGroups:
  - clustersecret.pocteo.com
  resources:
  - clustersecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustersecret.pocteo.com
  resources:
  - clustersecrets/status
  verbs:
  - get
