# This rule is not used by the project cluster-secret-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to clustersecret.pocteo.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-secret-controller
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-viewer-role
rules:
- apiGroups:
  - clustersecret.pocteo.com
  resources:
  - clustersecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustersecret.pocteo.com
  resources:
  - clustersecrets/status
  verbs:
  - get
