apiVersion: v1
kind: Namespace
metadata:
  name: secrets
---
apiVersion: clustersecret.pocteo.com/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: secrets
spec:
  type: Opaque
  matchNamespace:
    - "ns1-*"
    - "ns2-*"
  data:
    username: YXppeg==
    password: YmNoaW5p
