apiVersion: clustersecret.pocteo.com/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: common-config
spec:
  type: Opaque
  matchNamespace:
    - "dev-*"
    # - "prod-*"
  data:
    username: ZmFrZV9heml6
    password: YmNoaW5p
