apiVersion: clustersecret.pocteo.com/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: common-config
matchNamespace:
  - "dev-*"
  - "prod-*"
type: Opaque
data:
  username: ZmFrZV9heml6X3VzZXJuYW1l
  password: ZmFrZV9heml6X3Bhc3N3b3Jk
