apiVersion: clustersecret.pocteo.com/v1
kind: ClusterSecret
metadata:
  labels:
    app.kubernetes.io/name: cluster-secret-controller
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-sample
spec:
  # TODO(user): Add fields here
